launch error
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
c:\users\user\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\ops.py in _create_c_op(graph, node_def, inputs, control_inputs)
   1625   try:
-> 1626     c_op = c_api.TF_FinishOperation(op_desc)
   1627   except errors.InvalidArgumentError as e:

InvalidArgumentError: Negative dimension size caused by subtracting 2 from 1 for 'max_pooling2d_1/MaxPool' (op: 'MaxPool') with input shapes: [?,1,28,20].

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-6-d485a6c5d742> in <module>
----> 1 model = LeNet.build(input_shape = INPUT_SHAPE, classes = NB_CLASSES)
      2 
      3 model.compile(loss = 'categorical_crossentropy', optimizer = OPTIMIZER
      4               , metrics = ["accuracy"])
      5 

<ipython-input-3-0e034974a82e> in build(input_shape, classes)
      5         model.add(Conv2D(20, kernel_size = 5, padding = "same", input_shape = input_shape ))
      6         model.add(Activation("relu"))
----> 7         model.add(MaxPooling2D(pool_size = (2, 2), strides = (2,2)))
      8         model.add(Conv2D(50, kernel_size = 5, border_mode = "same"))
      9         model.add(Activation("relu"))

c:\users\user\appdata\local\programs\python\python36\lib\site-packages\keras\engine\sequential.py in add(self, layer)
    179                 self.inputs = network.get_source_inputs(self.outputs[0])
    180         elif self.outputs:
--> 181             output_tensor = layer(self.outputs[0])
    182             if isinstance(output_tensor, list):
    183                 raise TypeError('All layers in a Sequential model '

c:\users\user\appdata\local\programs\python\python36\lib\site-packages\keras\engine\base_layer.py in __call__(self, inputs, **kwargs)
    455             # Actually call the layer,
    456             # collecting output(s), mask(s), and shape(s).
--> 457             output = self.call(inputs, **kwargs)
    458             output_mask = self.compute_mask(inputs, previous_mask)
    459 

c:\users\user\appdata\local\programs\python\python36\lib\site-packages\keras\layers\pooling.py in call(self, inputs)
    203                                         strides=self.strides,
    204                                         padding=self.padding,
--> 205                                         data_format=self.data_format)
    206         return output
    207 

c:\users\user\appdata\local\programs\python\python36\lib\site-packages\keras\layers\pooling.py in _pooling_function(self, inputs, pool_size, strides, padding, data_format)
    266         output = K.pool2d(inputs, pool_size, strides,
    267                           padding, data_format,
--> 268                           pool_mode='max')
    269         return output
    270 

c:\users\user\appdata\local\programs\python\python36\lib\site-packages\keras\backend\tensorflow_backend.py in pool2d(x, pool_size, strides, padding, data_format, pool_mode)
   3976         x = tf.nn.max_pool(x, pool_size, strides,
   3977                            padding=padding,
-> 3978                            data_format=tf_data_format)
   3979     elif pool_mode == 'avg':
   3980         x = tf.nn.avg_pool(x, pool_size, strides,

c:\users\user\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\ops\nn_ops.py in max_pool(value, ksize, strides, padding, data_format, name)
   2162         padding=padding,
   2163         data_format=data_format,
-> 2164         name=name)
   2165 
   2166 

c:\users\user\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py in max_pool(input, ksize, strides, padding, data_format, name)
   5080     _, _, _op = _op_def_lib._apply_op_helper(
   5081         "MaxPool", input=input, ksize=ksize, strides=strides, padding=padding,
-> 5082         data_format=data_format, name=name)
   5083     _result = _op.outputs[:]
   5084     _inputs_flat = _op.inputs

c:\users\user\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\op_def_library.py in _apply_op_helper(self, op_type_name, name, **keywords)
    785         op = g.create_op(op_type_name, inputs, output_types, name=scope,
    786                          input_types=input_types, attrs=attr_protos,
--> 787                          op_def=op_def)
    788       return output_structure, op_def.is_stateful, op
    789 

c:\users\user\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\util\deprecation.py in new_func(*args, **kwargs)
    486                 'in a future version' if date is None else ('after %s' % date),
    487                 instructions)
--> 488       return func(*args, **kwargs)
    489     return tf_decorator.make_decorator(func, new_func, 'deprecated',
    490                                        _add_deprecated_arg_notice_to_docstring(

c:\users\user\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\ops.py in create_op(***failed resolving arguments***)
   3270           input_types=input_types,
   3271           original_op=self._default_original_op,
-> 3272           op_def=op_def)
   3273       self._create_op_helper(ret, compute_device=compute_device)
   3274     return ret

c:\users\user\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\ops.py in __init__(self, node_def, g, inputs, output_types, control_inputs, input_types, original_op, op_def)
   1788           op_def, inputs, node_def.attr)
   1789       self._c_op = _create_c_op(self._graph, node_def, grouped_inputs,
-> 1790                                 control_input_ops)
   1791 
   1792     # Initialize self._outputs.

c:\users\user\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\ops.py in _create_c_op(graph, node_def, inputs, control_inputs)
   1627   except errors.InvalidArgumentError as e:
   1628     # Convert to ValueError for backwards compatibility.
-> 1629     raise ValueError(str(e))
   1630 
   1631   return c_op

ValueError: Negative dimension size caused by subtracting 2 from 1 for 'max_pooling2d_1/MaxPool' (op: 'MaxPool') with input shapes: [?,1,28,20].